export const To = {
  Home: '/',
  Login: '/login',
  ChangePassword: '/change-password',
  IAMHome: '/IAM',
  IAMUserList: '/IAM/user',
  IAMRoleList: '/IAM/role',
  IAMRoleCreate: '/IAM/role/create',
  IAMPermissionList: '/IAM/permission',
  IAMPermissionCreate: '/IAM/permission/create',
  CommerceHome: '/commerce',
  MDMHome: '/MDM',
  // 구성
  // 조직정보
  MDMConfigOrg: '/MDM/config/Org',
  MDMConfigOrgCreate: '/MDM/config/Org/Create',

  MDMConfigFactory: '/MDM/config/Factory',
  MDMConfigFactoryCreate: '/MDM/config/Factory/Create',
  MDMConfigWarehouse: '/MDM/config/Warehouse',
  MDMConfigArea: '/MDM/config/Area',
  MDMConfigLocation: '/MDM/config/Location',
  // 원부자재/제상품
  MDMGoodsMaterial: '/MDM/goods/material',
  MDMGoodsMaterialCreate: '/MDM/goods/material/create',
  MDMGoodsProduct: '/MDM/goods/product',
  MDMGoodsProductCreate: '/MDM/goods/product/create',
  MDMGoodsMaterialPurchasePrice: '/MDM/goods/material-purchase-price',
  MDMGoodsProductPurchasePrice: '/MDM/goods/product-purchase-price',
  MDMGoodsMaterialSellingPrice: '/MDM/goods/material-selling-price',
  // 회원
  CommerceMemberList: '/commerce/member',
  // 문의
  CommerceInquiry: '/commerce/inquiry',
  Commerce1on1List: '/commerce/1on1',
  CommerceFaqList: '/commerce/faq',
  // 공지
  CommerceNoticeList: '/commerce/notice',
  CommerceNoticeCreate: '/commerce/notice/create',
  // 리뷰
  CommerceReviewList: '/commerce/review',
  // 상품
  CommerceProductList: '/commerce/product',
  CommerceProductCreate: '/commerce/product/create',
  CommerceRestockNotiList: '/commerce/restock-noti',
  // 전시
  CommerceExhibit: '/commerce/exhibit',
  CommerceExhibitCategoryList: '/commerce/exhibit/category',
  CommerceExhibitBrandList: '/commerce/exhibit/brand',
  CommerceExhibitSpecialList: '/commerce/exhibit/special',
  CommerceExhibitHome: '/commerce/exhibit/home',
  CommerceExhibitHomePopup: '/commerce/exhibit/home-popup',
  // 검색
  CommerceSearch: '/commerce/search',
  CommerceSearchPopularList: '/commerce/search/popular',
  CommerceSearchRealTimeList: '/commerce/search/real-time',
  // 적립금
  CommercePoint: '/commerce/point',
  // 쿠폰
  CommerceCouponList: '/commerce/coupon',
  CommerceCouponCreate: '/commerce/coupon/create',
  // 마케팅/프로모션
  CommerceMarketingCouponList: '/commerce/marketing/coupon',
  CommerceMarketingPromotionList: '/commerce/marketing/promotion',
  CommerceMarketingEventList: '/commerce/marketing/event',
  // 알림
  CommerceNoti: '/commerce/noti',
  CommerceNotiFCM: '/commerce/noti/FCM',
  CommerceNotiMessage: '/commerce/noti/Message',
  CommerceNotiTalk: '/commerce/noti/talk',
  // 주문
  CommerceOrderList: '/commerce/order',
  // 결제
  CommercePaymentList: '/commerce/payment',

  // 반품/교환
  CommerceTakeBackList: '/commerce/take-back',
  // 기초정보
  CommerceInfo: '/commerce/info',
  Error: '/error',
}
