enum ErrorCode {
  ERR_NETWORK = 'ERR_NETWORK',
  ACCESS_DENIED = 'ACCESS_DENIED',
  ACCESS_DENIED_ACCOUNT_DISABLE = 'ACCESS_DENIED_ACCOUNT_DISABLE',
  INVALID_PARAMETERS = 'INVALID_PARAMETERS',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  TOKEN_INVALID_FORMAT = 'TOKEN_INVALID_FORMAT',
  FAILED_INTERNAL_ERROR = 'FAILED_INTERNAL_ERROR',
  FAILED_KEYCLOAK_HANDLING = 'FAILED_KEYCLOAK_HANDLING',
  RESOLVE_REQUIRED_ACTIONS = 'RESOLVE_REQUIRED_ACTIONS',
  EXISTING_ROLE_NAME = 'EXISTING_ROLE_NAME',
  EXISTING_PERMISSION_NAME = 'EXISTING_PERMISSION_NAME',
}

export default ErrorCode
