name: pr_script_test

on:
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: [self-hosted, ubuntu-latest, ARM64]
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: storybook build
        run: pnpm build-storybook

#      - name: dev build
#        run: pnpm run build:dev
#
#      - name: prod build
#        run: pnpm run build:prod

